CREATE TABLE ListByType ( [ListType] varchar(15), [Value] varchar(30), [Description] nvarchar(50) );
GO
INSERT INTO ListByType
VALUES
( 'CourtSearchList', 'OKADAC1   ', N'' ), 
( 'CourtSearchList', 'OKADAD1   ', N'' ), 
( 'CourtSearchList', 'OKALFC1   ', N'' ), 
( 'CourtSearchList', 'OKALFD1   ', N'' ), 
( 'CourtSearchList', 'OKATOC1   ', N'' ), 
( 'CourtSearchList', 'OKATOD1   ', N'' ), 
( 'CourtSearchList', 'OKBEAC1   ', N'' ), 
( 'CourtSearchList', 'OKBEAD1   ', N'' ), 
( 'CourtSearchList', 'OKBECC1   ', N'' ), 
( 'CourtSearchList', 'OKBECD1   ', N'' ), 
( 'CourtSearchList', 'OKBLAC1   ', N'' ), 
( 'CourtSearchList', 'OKBLAD1   ', N'' ), 
( 'CourtSearchList', 'OKBRYC1   ', N'' ), 
( 'CourtSearchList', 'OKBRYD1   ', N'' ), 
( 'CourtSearchList', 'OKCADC1   ', N'' ), 
( 'CourtSearchList', 'OKCADD1   ', N'' ), 
( 'CourtSearchList', 'OKCANC1   ', N'' ), 
( 'CourtSearchList', 'OKCAND1   ', N'' ), 
( 'CourtSearchList', 'OKCARC1   ', N'' ), 
( 'CourtSearchList', 'OKCARD1   ', N'' ), 
( 'CourtSearchList', 'OKCHEC1   ', N'' ), 
( 'CourtSearchList', 'OKCHED1   ', N'' ), 
( 'CourtSearchList', 'OKCHOC1   ', N'' ), 
( 'CourtSearchList', 'OKCHOD1   ', N'' ), 
( 'CourtSearchList', 'OKCIMC1   ', N'' ), 
( 'CourtSearchList', 'OKCIMD1   ', N'' ), 
( 'CourtSearchList', 'OKCLEC1   ', N'' ), 
( 'CourtSearchList', 'OKCLED1   ', N'' ), 
( 'CourtSearchList', 'OKCOAC1   ', N'' ), 
( 'CourtSearchList', 'OKCOAD1   ', N'' ), 
( 'CourtSearchList', 'OKCOMC1   ', N'' ), 
( 'CourtSearchList', 'OKCOMD1   ', N'' ), 
( 'CourtSearchList', 'OKCOTC1   ', N'' ), 
( 'CourtSearchList', 'OKCOTD1   ', N'' ), 
( 'CourtSearchList', 'OKCRAC1   ', N'' ), 
( 'CourtSearchList', 'OKCRAD1   ', N'' ), 
( 'CourtSearchList', 'OKCREC1   ', N'' ), 
( 'CourtSearchList', 'OKCRED1   ', N'' ), 
( 'CourtSearchList', 'OKCRED2   ', N'' ), 
( 'CourtSearchList', 'OKCRED3   ', N'' ), 
( 'CourtSearchList', 'OKCUSC1   ', N'' ), 
( 'CourtSearchList', 'OKCUSD1   ', N'' ), 
( 'CourtSearchList', 'OKDELC1   ', N'' ), 
( 'CourtSearchList', 'OKDELD1   ', N'' ), 
( 'CourtSearchList', 'OKDEWC1   ', N'' ), 
( 'CourtSearchList', 'OKDEWD1   ', N'' ), 
( 'CourtSearchList', 'OKELLC1   ', N'' ), 
( 'CourtSearchList', 'OKELLD1   ', N'' ), 
( 'CourtSearchList', 'OKGARC1   ', N'' ), 
( 'CourtSearchList', 'OKGARD1   ', N'' ), 
( 'CourtSearchList', 'OKGAVC1   ', N'' ), 
( 'CourtSearchList', 'OKGAVD1   ', N'' ), 
( 'CourtSearchList', 'OKGRAC1   ', N'' ), 
( 'CourtSearchList', 'OKGRAD1   ', N'' ), 
( 'CourtSearchList', 'OKGREC1   ', N'' ), 
( 'CourtSearchList', 'OKGRED1   ', N'' ), 
( 'CourtSearchList', 'OKGRNC1   ', N'' ), 
( 'CourtSearchList', 'OKGRND1   ', N'' ), 
( 'CourtSearchList', 'OKHAPC1   ', N'' ), 
( 'CourtSearchList', 'OKHAPD1   ', N'' ), 
( 'CourtSearchList', 'OKHARC1   ', N'' ), 
( 'CourtSearchList', 'OKHARD1   ', N'' ), 
( 'CourtSearchList', 'OKHASC1   ', N'' ), 
( 'CourtSearchList', 'OKHASD1   ', N'' ), 
( 'CourtSearchList', 'OKHUGC1   ', N'' ), 
( 'CourtSearchList', 'OKHUGD1   ', N'' ), 
( 'CourtSearchList', 'OKJACC1   ', N'' ), 
( 'CourtSearchList', 'OKJACD1   ', N'' ), 
( 'CourtSearchList', 'OKJEFC1   ', N'' ), 
( 'CourtSearchList', 'OKJEFD1   ', N'' ), 
( 'CourtSearchList', 'OKJOHC1   ', N'' ), 
( 'CourtSearchList', 'OKJOHD1   ', N'' ), 
( 'CourtSearchList', 'OKKAYC1   ', N'' ), 
( 'CourtSearchList', 'OKKAYD1   ', N'' ), 
( 'CourtSearchList', 'OKKAYD2   ', N'' ), 
( 'CourtSearchList', 'OKKAYD3   ', N'' ), 
( 'CourtSearchList', 'OKKINC1   ', N'' ), 
( 'CourtSearchList', 'OKKIND1   ', N'' ), 
( 'CourtSearchList', 'OKKIOC1   ', N'' ), 
( 'CourtSearchList', 'OKKIOD1   ', N'' ), 
( 'CourtSearchList', 'OKLATC1   ', N'' ), 
( 'CourtSearchList', 'OKLATD1   ', N'' ), 
( 'CourtSearchList', 'OKLEXC1   ', N'' ), 
( 'CourtSearchList', 'OKLEXD1   ', N'' ), 
( 'CourtSearchList', 'OKLINC1   ', N'' ), 
( 'CourtSearchList', 'OKLIND1   ', N'' ), 
( 'CourtSearchList', 'OKLOGC1   ', N'' ), 
( 'CourtSearchList', 'OKLOGD1   ', N'' ), 
( 'CourtSearchList', 'OKLOVC1   ', N'' ), 
( 'CourtSearchList', 'OKLOVD1   ', N'' ), 
( 'CourtSearchList', 'OKMAJC1   ', N'' ), 
( 'CourtSearchList', 'OKMAJD1   ', N'' ), 
( 'CourtSearchList', 'OKMARC1   ', N'' ), 
( 'CourtSearchList', 'OKMARD1   ', N'' ), 
( 'CourtSearchList', 'OKMAYC1   ', N'' ), 
( 'CourtSearchList', 'OKMAYD1   ', N'' ), 
( 'CourtSearchList', 'OKMCCC1   ', N'' ), 
( 'CourtSearchList', 'OKMCCD1   ', N'' ), 
( 'CourtSearchList', 'OKMCIC1   ', N'' ), 
( 'CourtSearchList', 'OKMCID1   ', N'' ), 
( 'CourtSearchList', 'OKMCUC1   ', N'' ), 
( 'CourtSearchList', 'OKMCUD1   ', N'' ), 
( 'CourtSearchList', 'OKMURC1   ', N'' ), 
( 'CourtSearchList', 'OKMURD1   ', N'' ), 
( 'CourtSearchList', 'OKMUSC1   ', N'' ), 
( 'CourtSearchList', 'OKMUSD1   ', N'' ), 
( 'CourtSearchList', 'OKNOBC1   ', N'' ), 
( 'CourtSearchList', 'OKNOBD1   ', N'' ), 
( 'CourtSearchList', 'OKNOWC1   ', N'' ), 
( 'CourtSearchList', 'OKNOWD1   ', N'' ), 
( 'CourtSearchList', 'OKOKFC1   ', N'' ), 
( 'CourtSearchList', 'OKOKFD1   ', N'' ), 
( 'CourtSearchList', 'OKOKLC1   ', N'' ), 
( 'CourtSearchList', 'OKOKLD1   ', N'' ), 
( 'CourtSearchList', 'OKOKMC1   ', N'' ), 
( 'CourtSearchList', 'OKOKMD1   ', N'' ), 
( 'CourtSearchList', 'OKOKMD2   ', N'' ), 
( 'CourtSearchList', 'OKOSAC1   ', N'' ), 
( 'CourtSearchList', 'OKOSAD1   ', N'' ), 
( 'CourtSearchList', 'OKOTTC1   ', N'' ), 
( 'CourtSearchList', 'OKOTTD1   ', N'' ), 
( 'CourtSearchList', 'OKPAWC1   ', N'' ), 
( 'CourtSearchList', 'OKPAWD1   ', N'' ), 
( 'CourtSearchList', 'OKPAYC1   ', N'' ), 
( 'CourtSearchList', 'OKPAYD1   ', N'' ), 
( 'CourtSearchList', 'OKPITC1   ', N'' ), 
( 'CourtSearchList', 'OKPITD1   ', N'' ), 
( 'CourtSearchList', 'OKPONC1   ', N'' ), 
( 'CourtSearchList', 'OKPOND1   ', N'' ), 
( 'CourtSearchList', 'OKPOTC1   ', N'' ), 
( 'CourtSearchList', 'OKPOTD1   ', N'' ), 
( 'CourtSearchList', 'OKPUSC1   ', N'' ), 
( 'CourtSearchList', 'OKPUSD1   ', N'' ), 
( 'CourtSearchList', 'OKROEC1   ', N'' ), 
( 'CourtSearchList', 'OKROED1   ', N'' ), 
( 'CourtSearchList', 'OKROGC1   ', N'' ), 
( 'CourtSearchList', 'OKROGD1   ', N'' ), 
( 'CourtSearchList', 'OKSEMC1   ', N'' ), 
( 'CourtSearchList', 'OKSEMD1   ', N'' ), 
( 'CourtSearchList', 'OKSEMD2   ', N'' ), 
( 'CourtSearchList', 'OKSEQC1   ', N'' ), 
( 'CourtSearchList', 'OKSEQD1   ', N'' ), 
( 'CourtSearchList', 'OKSTEC1   ', N'' ), 
( 'CourtSearchList', 'OKSTED1   ', N'' ), 
( 'CourtSearchList', 'OKTEXC1   ', N'' ), 
( 'CourtSearchList', 'OKTEXD1   ', N'' ), 
( 'CourtSearchList', 'OKTILC1   ', N'' ), 
( 'CourtSearchList', 'OKTILD1   ', N'' ), 
( 'CourtSearchList', 'OKTULC1   ', N'' ), 
( 'CourtSearchList', 'OKTULD1   ', N'' ), 
( 'CourtSearchList', 'OKWAGC1   ', N'' ), 
( 'CourtSearchList', 'OKWAGD1   ', N'' ), 
( 'CourtSearchList', 'OKWAHC1   ', N'' ), 
( 'CourtSearchList', 'OKWAHD1   ', N'' ), 
( 'CourtSearchList', 'OKWASC1   ', N'' ), 
( 'CourtSearchList', 'OKWASD1   ', N'' ), 
( 'CourtSearchList', 'OKWODC1   ', N'' ), 
( 'CourtSearchList', 'OKWODD1   ', N'' ), 
( 'CourtSearchList', 'OKWOOC1   ', N'' ), 
( 'CourtSearchList', 'OKWOOD1   ', N'' ), 
( 'CourtTypeList', 'C', N'Clerk / Auditor / Recorder' ), 
( 'CourtTypeList', 'D', N'District / Superior / Circuit' ), 
( 'FileTypeList', 'AJ', N'JUDGMENT LIEN' ), 
( 'FileTypeList', 'AR', N'JUDGMENT LIEN RELEASE' ), 
( 'FileTypeList', 'BN', N'CIVIL NEW FILING' ), 
( 'FileTypeList', 'CD', N'CIVIL DISMISSAL' ), 
( 'FileTypeList', 'CF', N'CORRECTED FEDERAL TAX LIEN' ), 
( 'FileTypeList', 'CJ', N'CIVIL JUDGMENT' ), 
( 'FileTypeList', 'CS', N'CIVIL SPECIAL JUDGMENT' ), 
( 'FileTypeList', 'FD', N'FORCIBLE ENTRY/DETAINER' ), 
( 'FileTypeList', 'FE', N'FILED IN ERROR-FED TAX LIEN' ), 
( 'FileTypeList', 'FR', N'FEDERAL TAX LIEN RELEASE' ), 
( 'FileTypeList', 'FT', N'FEDERAL TAX LIEN' ), 
( 'FileTypeList', 'RD', N'FORCIBLE ENTRY/DETAINER RELEAS' ), 
( 'FileTypeList', 'RL', N'CIVIL JUDGMENT RELEASE' ), 
( 'FileTypeList', 'RM', N'CIVIL SPECIAL JUDGMENT RELEASE' ), 
( 'FileTypeList', 'RS', N'SMALL CLAIMS JUDGMENT RELEASE' ), 
( 'FileTypeList', 'SC', N'SMALL CLAIMS JUDGMENT' ), 
( 'FileTypeList', 'TW', N'STATE TAX WARRANT' ), 
( 'FileTypeList', 'VJ', N'VACATED JUDGMENT' ), 
( 'FileTypeList', 'WE', N'FILED IN ERROR-ST TAX WARRANT' ), 
( 'FileTypeList', 'WR', N'STATE TAX WARRANT RELEASE' ), 
( 'SupplierList', '16', N'MILLER RESEARCH, LLC' ), 
( 'SupplierList', '32', N'QUICK COURT LINKS' );

